/*
 * generated by Xtext
 */
package de.deg.eler.ft.vp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends de.deg.eler.ft.vp.AbstractDslRuntimeModule {

}
