/*
 * generated by Xtext
 */
package de.deg.eler.ft.vp.ui.contentassist

import de.deg.eler.ft.vp.ui.contentassist.AbstractDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DslProposalProvider extends AbstractDslProposalProvider {
}
