/*
* generated by Xtext
*/
package de.deg.eler.ft.vp;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.deg.eler.ft.vp.ui.internal.DslActivator.getInstance().getInjector("de.deg.eler.ft.vp.Dsl");
	}
	
}
