/*
* generated by Xtext
*/
package de.deg.eler.ft.vp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/deg/eler/ft/vp/parser/antlr/internal/InternalDsl.tokens");
	}
}
